import React from "react";
import "../../globals.css";
import Header from "@/component/Header";

export const metadata = {
  title: 'Login | Lofi Typing',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
